version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx_container
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    working_dir: /work
    tty: true
    stdin_open: true
